// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pipeline

type Document struct {
	ID           int64
	DriveFileID  string
	Filename     string
	Filepath     string
	Content      string
	Extension    string
	LastModified string
	SizeBytes    int64
}

type DocumentsFt struct {
	Filename string
	Content  string
}
